### ISSUE TITLE
请问如何打包gui

### ISSUE THREAD

**Issue by L1cardo** [Ikaros-521/bilibili_draw#1]
我是macOS系统 我想自己打包一个gui，请问如何操作

**Comment by Ikaros-521** [comment]
搭建python3的环境，装pyinstaller，然后用pyinstaller打包

**Comment by L1cardo** [comment]
十分抱歉打扰了，好像其实直接运行`gui_draw.py`就可以，会直接调用python自带的tkinter来显示gui

**Comment by L1cardo** [comment]
但是还有一个问题，同样的动态链接，用`gui_draw.py`就没问题，但是使用bili_draw.py就会出现错误，错误如下
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/33802186/171212959-923431b0-f12c-4ae7-b3e8-833f291c124c.png">

**Comment by Ikaros-521** [comment]
> 



> 但是还有一个问题，同样的动态链接，用`gui_draw.py`就没问题，但是使用bili_draw.py就会出现错误，错误如下 <img alt="image" width="1060" src="https://user-images.githubusercontent.com/33802186/171212959-923431b0-f12c-4ae7-b3e8-833f291c124c.png">

对，因为b站api改了，我前几天刚改了gui版本的源码，旧版cmd版还没改，准备弃用了
其实改的不多，oid的接口改了

**Comment by Ikaros-521** [comment]
> 但是还有一个问题，同样的动态链接，用`gui_draw.py`就没问题，但是使用bili_draw.py就会出现错误，错误如下 <img alt="image" width="1060" src="https://user-images.githubusercontent.com/33802186/171212959-923431b0-f12c-4ae7-b3e8-833f291c124c.png">

req = urllib.request.urlopen('https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?%s' % data)
req = urllib.request.urlopen('https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/get_dynamic_detail?%s' % data)
这块

**Comment by L1cardo** [comment]
那请问以后您会主要更新哪一版？还是说整个项目都要弃用？

**Comment by Ikaros-521** [comment]
> 那请问以后您会主要更新哪一版？还是说整个项目都要弃用？

主要维护gui版本，js版本估计也会维护这

**Comment by L1cardo** [comment]
OK  感谢
